### ISSUE TITLE
Restriction Functions on tgeompoint vs tgeogpoint

### ISSUE THREAD

**Issue by chaitan94** [ULB-CoDE-WIT/MobilityDB#11]
So I have tried two similar queries using `atValue`, but with different results:

```
mobilitydb=# SELECT asText(atValue(tgeompoint '[Point(0 0 0)@2012-01-01, Point(2 2 2)@2012-01-03)', 'Point(1 1 1)'));
                   astext                   
--------------------------------------------
 {[POINT Z (1 1 1)@2012-01-02 00:00:00+00]}
(1 row)

mobilitydb=# SELECT asText(atValue(tgeogpoint '[Point(0 0 0)@2012-01-01, Point(2 2 2)@2012-01-03)', 'Point(1 1 1)'));
 astext 
--------
 
(1 row)
```

Is this expected behavior?

**Comment by estebanzimanyi** [comment]
Yes this is the expected behavior. Indeed MobilityDB delegates all spatial processing to PostGIS. The queries you sent to MobilityDB is equivalent to the following ones on PostGIS.

SELECT st_intersects(geometry 'Linestring Z(0 0 0,2 2 2)', geometry 'POINT Z(1 1 1)');
-- true
SELECT st_intersects(geography 'Linestring Z(0 0 0,2 2 2)', geography 'POINT Z(1 1 1)');
-- false

The reason for this is that is geometry uses planar coordinates while geography uses spherical coordinates.
