### ISSUE TITLE
linestring instead of point?

### ISSUE THREAD

**Issue by wendellwt** [ULB-CoDE-WIT/MobilityDB#3]
Sirs,

Would it be possible to use 'linestring' instead of 'point' in the tgeompoint column?  Would it be advisable?

I would like to describe a path using linestrings, and then perform ST_Contains() or ST_Intersects() to identify intersections with a polygon.  The PostGIS ST_Intersect() works on a linestring geometry and that is what I'm currently using.  I would like to use of MobileDB to analyze this.  The addition of timestamps seems very interesting.

I suppose an issue would be the temporal aspect of the intersect.  Would I assume the timestamp of the linestring is that of the starting point or the ending point?

If there are _lots_ of points (such as from a GPS device), then it would be likely that one of the points was within the polygon.  I don't have all of those individual points, only a linestring between points along a route.

An alternative would be to use st_geod_segmentize() (one of R's spatial features functions) to create points along each linestring that would be 'smaller' than the polygon size.  Would that be a better solution?

(The problem: given an aircraft's planned route from departure to point A to point B to arrival, would it fly through a weather cell described by a polygon?  What time would it enter and leave the cell?)

Thank you,
Wendell

**Comment by estebanzimanyi** [comment]
Dear Wendell

Many thanks for your interest in MobilityDB. If I understand well you problem, what you need is to compute the temporal intersection of a moving point and a geometry. You can do this in MobilityDB, as shown in the following example

select tintersects(tgeompoint '[point(0 0)@2000-01-01, point(3 3)@2000-01-04]', geometry 'Polygon((1 1,1 2,2 2,2 1,1 1))');
-- "{[f@2000-01-01 00:00:00+01, t@2000-01-02 00:00:00+01, t@2000-01-03 00:00:00+01], (f@2000-01-03 00:00:00+01, f@2000-01-04 00:00:00+01]}"

Please notice that a moving point may enter and leave a geometry multiple times as shown in the following example

select tintersects(tgeompoint '[point(0 2)@2000-01-01, point(6 2)@2000-01-11]', geometry 'Polygon((1 0,1 1,2 3,3 1,4 3, 5 1,5 0,1 0))');
"{[f@2000-01-01 00:00:00+01, t@2000-01-03 12:00:00+01, t@2000-01-05 04:00:00+01], 
(f@2000-01-05 04:00:00+01, t@2000-01-06 20:00:00+01, t@2000-01-08 12:00:00+01], 
(f@2000-01-08 12:00:00+01, f@2000-01-11 00:00:00+01]}"

If you want to obtain the first and last instant at which at moving point intersects a geometry you can obtain them as follows

select period(atValue(tintersects(tgeompoint '[point(0 2)@2000-01-01, point(6 2)@2000-01-11]', geometry 'Polygon((1 0,1 1,2 3,3 1,4 3, 5 1,5 0,1 0))'), true))
"[2000-01-03 12:00:00+01, 2000-01-08 12:00:00+01]"

Regarding your question about using generic geometries instead of points in MobilityDB, the current version does not support them since all temporal operations (e.g. temporal intersection) are much more complex for moving geometries than for moving points. Nevertheless, we are already exploring the issue in order to implement OGC's Moving Features standard https://www.opengeospatial.org/standards/movingfeatures 
Therefore, yes, we will be able to support moving geometries (which are non deforming) in a future release of MobilityDB.

Regards

Esteban

**Comment by wendellwt** [comment]
Thank you for the reply.  I'll make use of MobilityDB with points that have timestamps.  That will be much better than PostGIS with the LinestringM.

Thanks again,
Wendell
