### ISSUE TITLE
Plans for PostGIS 3

### ISSUE THREAD

**Issue by sabman** [ULB-CoDE-WIT/MobilityDB#6]
Thanks for the awesome project. Quick question are we compatible with PostGIS 3 yet? If not are there plans?

**Comment by alesuiss** [comment]
Hi,

We currently do not support with PostGIS 3; we plan this for after our first major release, as it will require significant restructuring of the project.

**Comment by geography** [comment]
Hi all,

Thanks for the great project, there are any news about this topic?

Ema.

**Comment by estebanzimanyi** [comment]
Dear Ema

Many thanks for your interest in our project. We are wrapping up many
things to officially launch the first official MobilityDB 1.0 release and
then we tackle the integration with PostGIS 3.

Alas this is not an easy path, since PostGIS 3 does not export any longer
the liblwgeom library and having access to this C internal library is
essential to ensure the performance of MobilityDB. If instead we need to
access the SQL interface for every interaction with PostGIS this will
necessarily imply a performance penalty. We will need to collaborate with
the PostGIS team to see how we can solve this issue.

Regards

Esteban
